//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class APARTMENT
    {
        public int ApartmentId { get; set; }
        public int DeveloperId { get; set; }
        public string Address { get; set; }
        public int Size { get; set; }
        public int Beds { get; set; }
        public int Baths { get; set; }
        public int Price { get; set; }
        [DisplayName("Upload Image")]
        public string Picture { get; set; }
       
        public HttpPostedFileBase ImageFile { get; set; }
    
        public virtual DEVELOPER DEVELOPER { get; set; }
        public string Image { get; internal set; }
    }
}
