//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBmodel2Entities1 : DbContext
    {
        public DBmodel2Entities1()
            : base("name=DBmodel2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvanceMoney> AdvanceMoneys { get; set; }
        public virtual DbSet<APARTMENT> APARTMENTS { get; set; }
        public virtual DbSet<DEVELOPER> DEVELOPERS { get; set; }
        public virtual DbSet<RentalFlat> RentalFlats { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
