//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    

    public partial class DEVELOPER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVELOPER()
        {
            this.AdvanceMoneys = new HashSet<AdvanceMoney>();
            this.APARTMENTS = new HashSet<APARTMENT>();
            this.RentalFlats = new HashSet<RentalFlat>();
        }
        
        public int DeveloperId { get; set; }
        public string DeveloperName { get; set; }
        public string DeveloperEmail { get; set; }
        public string DeveloperPhone { get; set; }
        public string DeveloperPass { get; set; }
        public string License { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceMoney> AdvanceMoneys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APARTMENT> APARTMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalFlat> RentalFlats { get; set; }
    }
}
